//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pens.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacients
    {
        public long PacientID { get; set; }
        public string FIO { get; set; }
        public System.DateTime DateBirth { get; set; }
        public Nullable<long> OrgID { get; set; }
        public Nullable<long> PositionID { get; set; }
        public string Pasport { get; set; }
        public string Gender { get; set; }
        public string NoTK { get; set; }
        public Nullable<long> StRodID { get; set; }
        public string FIORod { get; set; }
    
        public virtual Organizations Organizations { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual StRod StRod { get; set; }
    }
}
