//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pens.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PensEntities : DbContext
    {
        public PensEntities()
            : base("name=PensEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branch> Branch { get; set; }
        public virtual DbSet<Docs> Docs { get; set; }
        public virtual DbSet<MKB> MKB { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<Pacients> Pacients { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Price> Price { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<StRod> StRod { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
